services:
  - type: web
    name: ultimo-parcial
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate --noinput
      python manage.py collectstatic --noinput
    startCommand: gunicorn parcial.wsgi
    plan: free
